<?php

namespace Database\Seeders;

use App\Models\Result;
use Illuminate\Database\Seeder;

class ResultsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         Result::create([
             'name' => '三振',
             'hit_flag' => false,
             'hit_2_flag' => false,
             'hit_3_flag' => false,
             'hr_flag' => false,
             'sansin_flag' => true,
             'heisatsu_flag' => false,
             'walk_flag' => false,
             'dead_flag' => false,
             'bant_flag' => false,
             'sac_fly_flag' => false,
             'out_count' => 1,
             'point_require_flag' => false,
             'dasu_count_flag' => true,
             'button_position' => 0,
             'button_type' => 1,
         ]);
         Result::create([
             'name' => '四球',
             'hit_flag' => false,
             'hit_2_flag' => false,
             'hit_3_flag' => false,
             'hr_flag' => false,
             'sansin_flag' => false,
             'heisatsu_flag' => false,
             'walk_flag' => true,
             'dead_flag' => false,
             'bant_flag' => false,
             'sac_fly_flag' => false,
             'out_count' => 0,
             'point_require_flag' => false,
             'dasu_count_flag' => false,
             'button_position' => 0,
             'button_type' => 2,
         ]);
         Result::create([
             'name' => '死球',
             'hit_flag' => false,
             'hit_2_flag' => false,
             'hit_3_flag' => false,
             'hr_flag' => false,
             'sansin_flag' => false,
             'heisatsu_flag' => false,
             'walk_flag' => false,
             'dead_flag' => true,
             'bant_flag' => false,
             'sac_fly_flag' => false,
             'out_count' => 0,
             'point_require_flag' => false,
             'dasu_count_flag' => false,
             'button_position' => 0,
             'button_type' => 2,
         ]);

         $positions = [
            1 => '投',
            2 => '捕',
            3 => '一',
            4 => '二',
            5 => '三',
            6 => '遊',
            7 => '左',
            8 => '中',
            9 => '右',
         ];
         foreach ($positions as $buttonPositionKey => $position) {
             Result::create([
                 'name' => $position . 'ゴ',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 1,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 1,

             ]);
             Result::create([
                 'name' => $position . '直',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 1,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 1,
             ]);
             Result::create([
                 'name' => $position . '飛',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 1,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 1,
             ]);
             Result::create([
                 'name' => $position . '併',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 2,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 1,
             ]);
             Result::create([
                 'name' => $position . 'FC',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 0,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 3,
             ]);

             Result::create([
                 'name' => $position . 'バ',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => true,
                 'sac_fly_flag' => false,
                 'out_count' => 1,
                 'point_require_flag' => false,
                 'dasu_count_flag' => false,
                'button_position' => $buttonPositionKey,
                 'button_type' => 2,
             ]);
             Result::create([
                 'name' => $position . 'バ失',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => true,
                 'sac_fly_flag' => false,
                 'out_count' => 0,
                 'point_require_flag' => false,
                 'dasu_count_flag' => false,
                'button_position' => $buttonPositionKey,
                 'button_type' => 2,
             ]);
             Result::create([
                 'name' => $position . '犠飛',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => true,
                 'out_count' => 1,
                 'point_require_flag' => false,
                 'dasu_count_flag' => false,
                'button_position' => $buttonPositionKey,
                 'button_type' => 2,
             ]);
             Result::create([
                 'name' => $position . '犠飛失',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => true,
                 'out_count' => 0,
                 'point_require_flag' => true,
                 'dasu_count_flag' => false,
                'button_position' => $buttonPositionKey,
                 'button_type' => 2,
             ]);
             Result::create([
                 'name' => $position . '失',
                 'hit_flag' => false,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => true,
                 'sac_fly_flag' => false,
                 'out_count' => 0,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 3,
             ]);
             Result::create([
                 'name' => $position . '安',
                 'hit_flag' => true,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 0,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 4,
             ]);
             Result::create([
                 'name' => $position . '二',
                 'hit_flag' => true,
                 'hit_2_flag' => true,
                 'hit_3_flag' => false,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 0,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 4,
             ]);
             Result::create([
                 'name' => $position . '三',
                 'hit_flag' => true,
                 'hit_2_flag' => false,
                 'hit_3_flag' => true,
                 'hr_flag' => false,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 0,
                 'point_require_flag' => false,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 4,
             ]);
             Result::create([
                 'name' => $position . '本',
                 'hit_flag' => true,
                 'hit_2_flag' => false,
                 'hit_3_flag' => false,
                 'hr_flag' => true,
                 'sansin_flag' => false,
                 'heisatsu_flag' => false,
                 'walk_flag' => false,
                 'dead_flag' => false,
                 'bant_flag' => false,
                 'sac_fly_flag' => false,
                 'out_count' => 0,
                 'point_require_flag' => true,
                 'dasu_count_flag' => true,
                'button_position' => $buttonPositionKey,
                 'button_type' => 4,
             ]);
         }
    }
}
